export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const EDIT_PROFILE_MODAL = 'EDIT_PROFILE_MODAL';
